spring:
  application:
    name: GameService
  cache:
    type: redis
  datasource:
    url: jdbc:postgresql://localhost:5432/GameChronicle
    username: postgres
    password: newton123
    driver-class-name: org.postgresql.Driver
